# Generated by Django 4.2.3 on 2023-07-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='image_gallery', max_length=20, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='image_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='LookupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='lookup_image')),
                ('attr1', models.CharField(blank=True, max_length=50, null=True)),
                ('attr2', models.CharField(blank=True, max_length=50, null=True)),
                ('attr3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='media', max_length=20, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='service_image')),
                ('attr1', models.CharField(blank=True, max_length=50, null=True)),
                ('attr2', models.CharField(blank=True, max_length=50, null=True)),
                ('attr3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
