# Generated by Django 4.2.3 on 2023-07-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='media_images')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
        migrations.RemoveField(
            model_name='mediagallery',
            name='image',
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='media_poster'),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='code',
            field=models.CharField(blank=True, default='media', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mediaimages',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mediagallery'),
        ),
    ]
